### ISSUE TITLE
seems the clean.py doesn't work, i get the error below.

### ISSUE THREAD

**Issue by GoodJoey** [hjacobs/kube-job-cleaner#11]
Traceback (most recent call last):
  File "/cleaner.py", line 101, in <module>
    main()
  File "/cleaner.py", line 93, in main
    for job in pykube.Job.objects(api, namespace=pykube.all):
  File "/usr/lib/python3.5/site-packages/pykube/query.py", line 133, in __iter__
    return iter(self.query_cache["objects"])
  File "/usr/lib/python3.5/site-packages/pykube/query.py", line 123, in query_cache
    cache["response"] = self.execute().json()
  File "/usr/lib/python3.5/site-packages/pykube/query.py", line 108, in execute
    r.raise_for_status()
  File "/usr/lib/python3.5/site-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://10.96.0.1:443/apis/batch/v1/jobs

seems the script doesn't have the authority to get the job list.
am I missing some step?

**Comment by mikkeloscar** [comment]
You must deploy it with a service account which has permissions to list jobs. Depending on your setup you most likely want to look into RBAC in Kubernetes which is the standard for authorization :)

**Comment by GoodJoey** [comment]
yup, thanks.

**Comment by novakg** [comment]
@GoodJoey were you able to make this work? Even if I assign a full admin role to the service account, I get the described error. And if I try to curl the given url from a busybox with the same service account, then I get:

```
/home # curl https://10.96.0.1:443/apis/batch/v1/jobs
curl: (77) error setting certificate verify locations:
  CAfile: /usr/share/ssl/certs/ca-bundle.crt
  CApath: none
/home # ls /usr/share/ssl/certs/ca-bundle.crt
ls: /usr/share/ssl/certs/ca-bundle.crt: No such file or directory
```
Any idea what am I doing wrong?
I'm using Kubernetes 1.10.2

**Comment by novakg** [comment]
FYI: I could solve the above issue with a ClusterRole:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "fullname" . }}
rules:
- apiGroups:
  - "*"
  resources:
  - jobs
  - pods
  verbs:
  - list
  - delete
```

a ClusterRoleBinding:

```
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ template "fullname" . }}
    namespace: {{ .Release.Namespace }}
```

and a ServiceAccount:

```
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: {{ template "fullname" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "fullname" . }}
```

and of course, adding that ServiceAccount to the job-cleaner's definition:

```
...
          containers:
          - name: cleaner
            image: hjacobs/kube-job-cleaner:{{ .Values.image.tag }}
            imagePullPolicy: IfNotPresent
            resources:
              limits:
                cpu: 200m
                memory: 100Mi
              requests:
                cpu: 50m
                memory: 50Mi
          serviceAccountName: {{ template "fullname" . }}
...
```

(Sorry for the templates in brackets, I defined these in a Helm chart.)
